# Generated by Django 6.0.1 on 2026-01-06 20:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MysteryContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(
                        choices=[("MV", "Movie"), ("TV", "TV Show")],
                        default="MV",
                        max_length=2,
                    ),
                ),
                ("release_year", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Mystery Title",
                "verbose_name_plural": "Mystery Titles",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_quality",
                    models.PositiveSmallIntegerField(
                        help_text="Rate the overall quality from 1 (Poor) to 5 (Masterpiece).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        help_text="How hard was it to solve? 1 (Obvious) to 5 (Impossible).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "is_fair_play",
                    models.BooleanField(
                        default=True,
                        help_text="Check this box if the viewer is given all the clues needed to solve the mystery alongside the detective.",
                        verbose_name="Fair Play Mystery",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Optional review comments."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="reviews.mysterycontent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mystery_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content", "user"), name="unique_user_content_review"
                    )
                ],
            },
        ),
    ]
