# Generated by Django 6.0.1 on 2026-01-21 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL friendly name (e.g. rian-johnson)', unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL friendly name (e.g. benoit-blanc)', unique=True)),
            ],
            options={
                'verbose_name_plural': 'series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='Can other users see this collection?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MysteryTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL friendly title (e.g. knives-out)', unique=True)),
                ('media_type', models.CharField(choices=[('MV', 'Movie'), ('TV', 'TV Show'), ('MS', 'Miniseries')], default='MV', max_length=2)),
                ('release_year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_fair_play_candidate', models.BooleanField(default=True, help_text='Is this title applicable for Fair Play analysis?')),
                ('avg_quality', models.FloatField(default=0.0, verbose_name='Quality Score')),
                ('avg_difficulty', models.FloatField(default=0.0, verbose_name='Difficulty Score')),
                ('fair_play_consensus', models.FloatField(default=0.0, help_text="Percentage of users who voted 'Fair'", verbose_name='Fair Play %')),
                ('director', models.ForeignKey(blank=True, help_text='Director or Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.director')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.series')),
            ],
            options={
                'verbose_name': 'Mystery Title',
                'verbose_name_plural': 'Mystery Titles',
                'ordering': ['-release_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Quality (1-5)')),
                ('difficulty', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Difficulty (1-5)')),
                ('is_fair_play', models.BooleanField(help_text='Was the mystery solvable with the clues provided?', verbose_name='Fair Play?')),
                ('solved', models.BooleanField(default=False, help_text='Did you solve the mystery before the reveal?', verbose_name='Solved?')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Helpful Votes')),
                ('not_helpful_count', models.PositiveIntegerField(default=0, verbose_name='Not Helpful Votes')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.mysterytitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpfulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(help_text='True if the user found this review helpful, False otherwise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='movies.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Helpful Vote',
                'verbose_name_plural': 'Review Helpful Votes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TagVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_votes', to='movies.mysterytitle')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='movies.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='movies.mysterytitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Watchlist entries',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, help_text='Why is this movie in the list?')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='movies.collection')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='movies.mysterytitle')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('collection', 'movie'), name='unique_collection_item')],
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('movie', 'user'), name='unique_review_per_user'),
        ),
        migrations.AddConstraint(
            model_name='reviewhelpfulvote',
            constraint=models.UniqueConstraint(fields=('review', 'user'), name='unique_helpful_vote_per_user'),
        ),
        migrations.AddConstraint(
            model_name='tagvote',
            constraint=models.UniqueConstraint(fields=('movie', 'tag', 'user'), name='unique_tag_vote'),
        ),
        migrations.AddConstraint(
            model_name='watchlistentry',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_watchlist_entry'),
        ),
    ]
