# Generated by Django 6.0.1 on 2026-01-08 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL friendly name (e.g. rian-johnson)', unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL friendly name (e.g. benoit-blanc)', unique=True)),
            ],
            options={
                'verbose_name_plural': 'series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MysteryTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL friendly title (e.g. knives-out)', unique=True)),
                ('media_type', models.CharField(choices=[('MV', 'Movie'), ('TV', 'TV Show'), ('MS', 'Miniseries')], default='MV', max_length=2)),
                ('release_year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_fair_play_candidate', models.BooleanField(default=True, help_text='Is this title applicable for Fair Play analysis?')),
                ('avg_quality', models.FloatField(default=0.0, verbose_name='Quality Score')),
                ('avg_difficulty', models.FloatField(default=0.0, verbose_name='Difficulty Score')),
                ('fair_play_consensus', models.FloatField(default=0.0, help_text="Percentage of users who voted 'Fair'", verbose_name='Fair Play %')),
                ('directors', models.ManyToManyField(help_text='Director or Creator', related_name='movies', to='movies.director')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.series')),
            ],
            options={
                'verbose_name': 'Mystery Title',
                'verbose_name_plural': 'Mystery Titles',
                'ordering': ['-release_year', 'title'],
            },
        ),
    ]
