# Generated by Django 6.0.1 on 2026-01-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL friendly name (e.g. rian-johnson)', unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='mysterytitle',
            name='director',
        ),
        migrations.AddField(
            model_name='mysterytitle',
            name='directors',
            field=models.ManyToManyField(help_text='Director or Creator', related_name='movies', to='movies.director'),
        ),
    ]
