# Generated by Django 6.0.1 on 2026-01-07 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_director_remove_mysterytitle_director_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL friendly name (e.g. benoit-blanc)', unique=True)),
            ],
            options={
                'verbose_name_plural': 'series',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='mysterytitle',
            options={'ordering': ['series', '-release_year', 'title'], 'verbose_name': 'Mystery Title', 'verbose_name_plural': 'Mystery Titles'},
        ),
        migrations.AddField(
            model_name='mysterytitle',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.series'),
        ),
    ]
